#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルの仕様: https://github.com/sevenc-nanashi/aviutl2-cli

[project]
id = "kantandanmaku"
name = "kantandanmaku"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[artifacts.kantandanmaku-auf2]
destination = "Plugin/kantandanmaku.auf2"

[artifacts.kantandanmaku-auf2.profiles.debug]
build = ["cargo build"]
source = "target/debug/kantandanmaku.dll"

[artifacts.kantandanmaku-auf2.profiles.release]
build = ["cargo build --release"]
source = "target/release/kantandanmaku.dll"

[artifacts.sample-readme]
source = "samples/README.md"
destination = "Script/弾幕生成フィルタ/README.md"

[artifacts.sample-touhou]
source = "samples/touhou_rotating_ring.rhai"
destination = "Script/弾幕生成フィルタ/touhou_rotating_ring.rhai"

[artifacts.sample-dodonpachi-daioujou]
source = "samples/dodonpachi_daioujou_aimed_fan.rhai"
destination = "Script/弾幕生成フィルタ/dodonpachi_daioujou_aimed_fan.rhai"

[artifacts.sample-mushihimesama]
source = "samples/mushihimesama_spiral_layers.rhai"
destination = "Script/弾幕生成フィルタ/mushihimesama_spiral_layers.rhai"
